#!/bin/bash
set -e

python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="infinity" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9

python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
python3 simulation.py --num_partitions=10 --adv_grad_norm="l2" --adv_multiplier=0.05 --adv_step_size=0.05 --batch_size=32 --epochs=5 --num_clients=10 --num_rounds=10 --federated_optimizer_strategy="fedavg" --adv_reg=True --gaussian_layer=True --pseudorandom_image_transformations=True --image_corruption_train=True --image_resolution_loss_train=True --formal_robustness_analysis=True --fraction_fit=0.05 --fraction_eval=0.5 --min_fit_clients=10 --min_eval_clients=10 --min_available_clients=2 --accept_client_failures_fault_tolerance=False --weight_regularization=False --sgd_momentum=0.9
